# name: Deploy Storybook

# on:
#   push:
#     branches:
#       - master
#   pull_request:

# jobs:
#   deploy:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#     #   - name: Install dependencies
#     #     run: yarn install

#     #   - name: Build Storybook
#     #     run: yarn storybook

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./storybook

